package com.example.mentalhealthapp;

import android.app.AlertDialog;
import android.content.Context;
import android.content.DialogInterface;
import android.content.Intent;
import android.util.Log;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.TextView;
import android.widget.Toast;

import androidx.annotation.NonNull;
import androidx.cardview.widget.CardView;
import androidx.recyclerview.widget.RecyclerView;

import java.util.ArrayList;
import java.util.zip.Inflater;

public class JournalPreviewAdapter extends RecyclerView.Adapter<JournalPreviewAdapter.viewHolder>{

    private JournalDatabase db;
    ArrayList<JournalEntry> journalEntries;
    Context c;

    public JournalPreviewAdapter(ArrayList<JournalEntry> journalEntries, Context c) {
        this.journalEntries = journalEntries;
        db=new JournalDatabase(c);
        this.c=c;
    }

    public void setJournalEntries(ArrayList<JournalEntry> journalEntries) {
        this.journalEntries = journalEntries;
        notifyDataSetChanged();
    }

    @NonNull
    @Override
    public viewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(parent.getContext()).inflate(R.layout.basic_item_layout_journal_main,parent,false);
        viewHolder holder=new viewHolder(view);
        return holder;
    }

    @Override
    public void onBindViewHolder(@NonNull viewHolder holder,int position) {
        //This holder is generated by Layout Manager and we have access to all fields in the inner class
        holder.title.setText(journalEntries.get(position).getTitle());
        holder.startLine.setText(journalEntries.get(position).getContent());

        holder.parentCard.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Toast.makeText(c,String.valueOf(journalEntries.get(holder.getAdapterPosition()).getId()),Toast.LENGTH_SHORT).show();
                Intent intent=new Intent(c,JournalView.class);
                intent.putExtra("title",journalEntries.get(holder.getAdapterPosition()).getTitle());
                intent.putExtra("content",journalEntries.get(holder.getAdapterPosition()).getContent());
                c.startActivity(intent);
            }
        });

        holder.btnDelete.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                new AlertDialog.Builder(c)
                        .setIcon(android.R.drawable.ic_delete)
                        .setTitle("Are you sure ?")
                        .setMessage("Do you want to delete this item")
                        .setPositiveButton("Yes", new DialogInterface.OnClickListener() {
                            @Override
                            public void onClick(DialogInterface dialogInterface, int i) {
                                boolean b = db.deleteJournal(journalEntries.get(holder.getAdapterPosition()).getContent());
                                Toast.makeText(c,"delete = "+b,Toast.LENGTH_SHORT).show();
                                journalEntries.remove(holder.getAdapterPosition());
                                setJournalEntries(journalEntries);
                            }
                        }).setNegativeButton("No",null).show();
            }
        });
    }

    @Override
    public int getItemCount() {
        return journalEntries.size();
    }

    public static class viewHolder extends RecyclerView.ViewHolder{

        private TextView title, startLine;
        private ImageButton btnDelete;
        private CardView parentCard;

        public viewHolder(@NonNull View itemView) {
            super(itemView);
            title=itemView.findViewById(R.id.txtTitleOfDiary);
            startLine=itemView.findViewById(R.id.txtPreviewOfDiary);
            btnDelete=itemView.findViewById(R.id.imgbtnDelete);
            parentCard=itemView.findViewById(R.id.cardViewJournal);
        }


    }
}
